### ISSUE TITLE
Upgrade RainbowKit to v2 (Wagmi + Viem included)

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/rollups-explorer#130]
## 📄 Context
CartesiScan uses Wagmi and Viem to do heavy lifting when talking to the blockchain. Both these libraries reached version 2 with breaking changes. Another library we use is RainbowKit, which uses both libs but only reached version 2 last month. Now, we can upgrade all of them. 

RainbowKit v2.0.0: [release notes](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%402.0.0)
Wagmi v2: [Migration guide](https://wagmi.sh/react/guides/migrate-from-v1-to-v2)
Viem v2: [Migration guide](https://viem.sh/docs/migration-guide.html#_2-x-x-breaking-changes)

## ✔️ Solution

There are two parts to this work: wallet configuration and code generation. Check the release notes and migration guides for reference. 

#### Wallet configuration affects:
* `apps/web`
* `apps/workshop`

#### Wagmi + View code generation affects:
* `apps/web`
* `apps/workshop` (may affect)
* `packages/rollups-wagmi`
* `packages/ui`

**PS: Keep the package.json definition we are currently using, e.g. `"wagmi": "1^"`, should then become `"wagmi": "2^"`. Make sure the yarn.lock has the correct version setup after the upgrade.**

### Wallet configuration
- [x] `apps/web`
  - [x] Upgrade RainbowKit, Wagmi and Viem to version 2, including any required new dependency.
  - [x] Refactor the wallet configuration. 
  - [x] Refactor any imports, functions and types that may change with the new version. 
- [x] `apps/workshop`
  - [x] Upgrade RainbowKit, Wagmi and Viem to version 2, including any required new dependency.
  - [x] Refactor the wallet configuration. 
  - [x] Refactor any imports, functions and types that may change with the new version.
 
### Code generation
- [x] `packages/rollups-wagmi`
  - [x] Upgrade Wagmi to version 2 and @wagmi/cli to a compatible version, including any new required dependency.
  - [x] Upgrade `sunodo/wagmi-plugin-hardhat-deploy` to its latest version.
  - [x] Adjustments to `wagmi.config`. (may be required)
- [x] `packages/ui`
  - [x] Upgrade Wagmi and Viem to version 2, including any required new dependency.
  - [x] Refactor as needed due to API and export changes.
  - [x] Refactor as needed if newly generated wagmi hooks changed (e.g. naming, arguments order, etc...).
- [x] `apps/web`
  - [x] Refactor as needed if newly generated wagmi hooks changed (e.g. naming, arguments order, etc...).
- [x] Refactor tests. Mainly, the mocks will be affected.
- [x] Make sure dependencies are updated in the lock file (yarn.lock).

## 🎯 Definition of Done

- [x] Web
  - [x] User can connect wallet (Metamask, Rainbow, Coinbase Wallet, Trust Wallet and Ledger)
  - [x] Wrong network status is displayed when the wallet is set to the wrong network. 
  - [x] User can complete an Ether deposit.
  - [x] User can complete an ERC-20 deposit.
  - [x] User can complete an ERC-721 deposit.
  - [x] User can send a `raw input` to a DApp. 
  - [x] User can do all the above when using CartesiScan https://app.safe.global/
  - [x] User can execute a voucher (devnet is ok)
- [x] Local and deployed Workshop has all the stories working.
- [x] Github CI is passing.
- [x] Vercel build is passing.

**Comment by brunomenezes** [comment]
@tuler, I included the upgrade of the sunodo plugin, I noticed on npmjs it is version 0.3.0, but not releases in the repo. 

I imagine this [compare](https://github.com/sunodo/wagmi-plugin-hardhat-deploy/compare/v0.2.0...main) is what is included at the moment on that published version. Are there any hiccups we need to be aware of?

**Comment by brunomenezes** [comment]
@nevendyulgerov, Feel free to add more subtasks as you see fit in case of discoveries during development.

**Comment by tuler** [comment]
> on npmjs it is version 0.3.0, but there is no release in the repo.

I’ll fix that. You can use 0.3.0.
