### ISSUE TITLE
Add validation for url field for connection form

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#135]
## 📄 Context

Currently, the url field in the connection form is not be validated for valid url. You can insert in it anything as long as it's not an empty string. We can improve that and validate the url field as well to ensure only valid graphql endpoints are being inserted in it. Here's a video demonstrating the current behavior:
https://github.com/cartesi/rollups-explorer/assets/6005179/3614b0bd-61df-4263-9a64-bbc76fa93494

## ✔️ Solution

We can validate the url using a custom regex or a third-party library to do the lifting for us.

## 🎯 Definition of Done

- [x] Url field is validated and connection form cannot be saved if an invalid url is inserted in it.
- [ ] Add test cases for this validation

**Comment by nevendyulgerov** [comment]
Hey @brunomenezes , @dandheedge , not sure if this should be labeled as a bug or feature request but I think it's nice if we tackle it. This will make the connection form a bit more strict and can prevent user error when inserting the graphql url. Please let me know your thoughts.

**Comment by dandheedge** [comment]
> Hey @brunomenezes , @dandheedge , not sure if this should be labeled as a bug or feature request but I think it's nice if we tackle it. This will make the connection form a bit more strict and can prevent user error when inserting the graphql url. Please let me know your thoughts.

Hi @nevendyulgerov, I consider this to be a new feature since it enhances the URL input validation process

**Comment by brunomenezes** [comment]
> Hey @brunomenezes , @dandheedge , not sure if this should be labeled as a bug or feature request but I think it's nice if we tackle it. This will make the connection form a bit more strict and can prevent user error when inserting the graphql url. Please let me know your thoughts.

We do url validation [here](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/connection/connectionForm.tsx#L93), so only a valid url will trigger the test request. That said, it is missing [here](https://github.com/cartesi/rollups-explorer/blame/main/apps/web/src/components/connection/connectionForm.tsx#L201) upon submission. Not sure if I like the idea of form error messages flashing while you’re typing, that is why the save is enabled , also I am not expecting users (developers) to type a invalid URL most of the time. So I would say is necessary fix but low priority compared with other issues.
