### ISSUE TITLE
ERC-20 deposit Token auto-complete

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-explorer#18]
## 📄 Context

The ERC-20 deposit form requires the input of the ERC-20 contract address.
The backend contains a list of Tokens, created from the past deposits.
We can use an auto-complete to help the user select the Token.
The backend contains not only the address of the ERC-20 but also the name and the symbol, which are very helpful for manual input.

## ✔️ Solution

We can use an [autocomplete](https://v7.mantine.dev/core/autocomplete) with information from the backend.
The query is something like the query below, but with variables for searching by address OR name OR symbol.

https://squid.subsquid.io/cartesi-rollups-sepolia/graphql

```graphql
query tokens {
  tokens {
    id
    name
    symbol
  }
}
```

Deposits to unknown tokens must be allowed, but we can present a warning box saying "this is the first deposit of that token".

## 📈 Subtasks

- [x] implement query
- [x] implement UI

## 🎯 Definition of Done

- [x] auto-complete working
- [x] warning presented if it's first deposit of that token

**Comment by nevendyulgerov** [comment]
This one depends on https://github.com/cartesi/rollups-explorer/issues/17 so we can start working on it as soon as the parent task is complete.
