### ISSUE TITLE
ERC-20 deposit Application auto-complete

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-explorer#19]
## 📄 Context

The ERC-20 deposit form requires the input of the application address.
The backend contains a list of Applications, created from the past inputs received and applications deployment.
We can use an auto-complete to help the user select the Application.

## ✔️ Solution

We can use an [autocomplete](https://v7.mantine.dev/core/autocomplete) with information from the backend.
The query is something like the query below, but with variables for searching by id.

https://squid.subsquid.io/cartesi-rollups-sepolia/graphql

```graphql
query applications {
  applications {
    id
  }
}
```

Deposits to unknown applications must be allowed, but we can present a warning box saying "this is a deposit to an undeployed application".

## 📈 Subtasks

- [x] implement query
- [x] implement UI
- [ ] 
## 🎯 Definition of Done

- [x] auto-complete working
- [x] warning presented if it's deposit to an unknown application

**Comment by nevendyulgerov** [comment]
This one depends on https://github.com/cartesi/rollups-explorer/issues/17 so we can start working on it as soon as the parent task is complete.
