### ISSUE TITLE
Display voucher destination

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-explorer#215]
## 📄 Context

As of Cartesi Rollups SDK v1, a voucher is made of two components: a destination and a payload.
The Web UI of the Rollups Explorer, however, only shows one of them: the payload.
The destination is a crucial part of the payload, it is who the contract will be calling.
From a payload, you may be able to know which Solidity function will be called, but not who.

![image](https://github.com/user-attachments/assets/c7ad5b50-8d3d-4dea-be99-0970abceeba3)

## ✔️ Solution

Add the destination address to the Web UI of vouchers.
A plus would be adding a link to the address in a trusted explorer, which may depend on the network.

**Comment by guidanoli** [comment]
Observation: For Cartesi Rollups SDK v2, vouchers will have one extra component: the amount of Wei that will be passed along the message call, which we usually call the "value". Furthermore, there will also be `DELEGATECALL` vouchers, which only have destination and payload. The destination is typically the address of a library, and the payload is also typically an encoded Solidity function call.

**Comment by guidanoli** [comment]
Also, IMO, it makes no sense to display the voucher as text or JSON. It normally encodes a Solidity function call. A safe way to better display vouchers would be to obtain the ABI of the destination contract through its address, and decode the payload as a function call, displaying all of its arguments, nicely typed, etc. What do you think, @tuler?

**Comment by tuler** [comment]
Related to https://github.com/cartesi/rollups-explorer/issues/156

**Comment by brunomenezes** [comment]
> Also, IMO, it makes no sense to display the voucher as text or JSON. It normally encodes a Solidity function call. A safe way to better display vouchers would be to obtain the ABI of the destination contract through its address, and decode the payload as a function call, displaying all of its arguments, nicely typed, etc. What do you think, @tuler?

I will close that one as it is related to #156 and #165. Once the issues are merged, we will display the decoded content as JSON.
