### ISSUE TITLE
Update alerts for transaction forms

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#222]
## 📄 Context

Currently, we use two types of alerts in the transaction forms to notify users that their transaction has succeeded. 

For example, in the Ether form, we use the `TransactionProgress` component to display the success information. In the ERC-721 form, we use the `notifications` api (from `mantine`) to display the success information.

Let's standardise the success UI and always display a notification on successful transaction as done for the ERC-721 form.

## ✔️ Solution

Use/extend the `onDeposit` (from `SendTransaction` component) callback so that all forms can use it to display a success notification after their transaction completed.

## 🎯 Definition of Done

- [ ] All transaction forms display a success notification on success.
- [ ] `TransactionProgress` component is still being in the transaction forms but only for displaying the loading/error state of the transaction.
- [ ] Add relevant tests

**Comment by nevendyulgerov** [comment]
Hi, @brunomenezes , can you please verify if this description is good enough for the notifications task?

**Comment by brunomenezes** [comment]
@nevendyulgerov, it looks good. I would suggest you have a look at that guy [here](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/sendTransaction.tsx#L70). When the transaction hash is available; it will publish a message with a link to the transaction on its related connected network block explorer.
