### ISSUE TITLE
"Max amount" field is confusing

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-explorer#43]
## 📄 Context

On the deposit form, there is a text field labeled "Max amount".
This may confuse the user into thinking they can edit it for some reason.

![Screenshot from 2023-11-02 07-50-07](https://github.com/cartesi/rollups-explorer/assets/9125226/dce6aa56-77d1-4b73-bad3-946e96d0edda)

## ✔️ Solution

Make the maximum amount be displayed through a read-only component, like a text component.
Preferably, this would sit near to the "Amount" field, that comes right after it.

**Comment by tuler** [comment]
I like the solution I did in another project to display the balance and the allowance.
<img width="482" alt="Screenshot 2023-11-02 at 3 49 31 PM" src="https://github.com/cartesi/rollups-explorer/assets/73850/f18c92d3-d54b-4834-9877-c9338cdf3d25">

**Comment by dandheedge** [comment]
> I like the solution I did in another project to display the balance and the allowance. <img alt="Screenshot 2023-11-02 at 3 49 31 PM" width="482" src="https://user-images.githubusercontent.com/73850/280097501-f18c92d3-d54b-4834-9877-c9338cdf3d25.png">

Hi @tuler, I want to confirm more about this feature. So, the `Balance` is for the amount of ERC20 token on our wallet. How about the `Allowance`? How do I get this figure?

**Comment by guidanoli** [comment]
> > I like the solution I did in another project to display the balance and the allowance. <img alt="Screenshot 2023-11-02 at 3 49 31 PM" width="482" src="https://user-images.githubusercontent.com/73850/280097501-f18c92d3-d54b-4834-9877-c9338cdf3d25.png">
> 
> Hi @tuler, I want to confirm more about this feature. So, the `Balance` is for the amount of ERC20 token on our wallet. How about the `Allowance`? How do I get this figure?

See `allowance(address,address)` from [EIP-20](https://eips.ethereum.org/EIPS/eip-20).
