### ISSUE TITLE
All-in-one deposit button

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-explorer#44]
## 📄 Context

Currently, AFAIK the production version of the explorer only supports ERC-20 deposits,
but it seems also that you are in the process of supporting Ether deposits as well.
Later, you might also give support to ERC-721 tokens (NFTs) and ERC-1155 tokens (Multi tokens).
My fear is that if all of these assets have their own individual deposit button, it might overcrowd the UI.

## ✔️ Solution

To solve this issue, we can make an all-in-one deposit button, which, when clicked, prompts the user to choose the specific type of asset they would like to deposit. It can be a pop-up component with buttons for each asset type, or a drop-down list streaming down from the deposit button...

**Comment by nevendyulgerov** [comment]
I think @guidanoli has a good point here. Hey, @brunomenezes , @tuler if you are ok with the suggested solution, I can start working on it. Please let me know.

**Comment by brunomenezes** [comment]
> I think @guidanoli has a good point here. Hey, @brunomenezes , @tuler if you are ok with the suggested solution, I can start working on it. Please let me know.

That is interesting, @guidanoli. Are these standards already in use on the DApp level? Is there a Dapp you tried to use one of these? 

I have been talking to @tuler about that crowded header, which we want to avoid having. For example, the create connection that is coming with Dapp-connect #41 is introducing a drawer where configs would live (e.g. there is a create custom ABI we'll experiment with soon that will also use that space). 

Nonetheless, that idea is not odd to me; when I worked on International Payments, the form would change based on (currency + country + specific bank country nuances) 

@nevendyulgerov, first, we need to get the following: #49 and #40 approved and merged before working on a new design.

**Comment by guidanoli** [comment]
> Are these standards already in use on the DApp level? Is there a Dapp you tried to use one of these?

I think Ether and ERC-20 are, by far, the most widely used types of assets. There are, however, some DApp that deal with NFTs (ERC-721 tokens). [Auction DApp](https://github.com/cartesi/rollups-examples/tree/main/auction) and [Tribes](https://github.com/felipefg/tribes) are some examples.

As for ERC-1155 tokens (multi-tokens), I don't know any example that uses them yet, but they are interesting for transferring tokens of different types in bulk. For example, imagine of an RPG where you have several resources (grain, ore, lumber, wool, clay). With ERC-1155, you can transfer resources of different types in a single transaction.

**Comment by juztamau5** [comment]
Ultrachess was thinking about using ERC-1155 to batch-transfer a chess set, with each piece wrapping a Uniswap v3 LP-NFT in a different liquidity range (narrowly spaced for pawns, wide liquidity range for kings). It's a future goal but still a concrete example of the value of ERC-1155 batch transfers.

**Comment by brunomenezes** [comment]
I will close this one as we work on a single UI supporting multiple forms ( #55). We will rearrange the ones we have (e.g., send raw input, deposit erc-20, deposit eth) and make room for more to come. Also, changing the text here and there since not all are `deposits`.

Thanks for the insightful issue @guidanoli and @juztamau5.
