### ISSUE TITLE
Improvements for forms

### ISSUE THREAD

**Issue by nevendyulgerov** [cartesi/rollups-explorer#53]
Improvements for forms, suggested by @brunomenezes :

I have two things to mention here. I agree with @tuler about the header shell fetching this kind of data. I think you could have a `<Deposit />` that encapsulates all the data needs of the form/forms (see where I am getting here? based on the suggestion on #44 ). The other thing that needs to be addressed is that `useApplicationsQuery`. Because requests with no limits will soon reach the imposed cardinalities in the backend, that will return errors like `response might exceed the size limit`. I also worked with application IDs and mentioned what I did on my current open PR #41. 

So my suggestions are : 

* Encapsulate your needs in a separate Component using the fetching data, modal and form/forms inside it
* look in my PR and adjust the query graphQL (that will come with my PR merged anyway) and use the limit for requesting only X amount of items to be more future-proof.

_Originally posted by @brunomenezes in https://github.com/cartesi/rollups-explorer/pull/36#discussion_r1387348732_

**Comment by brunomenezes** [comment]
Closing since the #55 was merged into #36.
